docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - "Quick Start": quick-start.md
    - "Tag Clouds": tag-cloud.md
site_name: zend-tag
site_description: Zend\Tag
repo_url: 'https://github.com/zendframework/zend-tag'
copyright: 'Copyright (c) 2005-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
